server {
    listen 9443 ssl;
    server_name api.guri24.com;

    ssl_certificate     /etc/letsencrypt/live/api.guri24.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.guri24.com/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # Proxy all requests to MinIO
    location / {
        proxy_pass         http://minio:9000;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_buffering    off;
        proxy_request_buffering off;
    }
}
