"""Sync verification_documents

Revision ID: 342abd7c0a4a
Revises: 7a8a4dbac98a
Create Date: 2026-01-18 12:17:03.453222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '342abd7c0a4a'
down_revision = '7a8a4dbac98a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('bookings')  <-- SAFETY: Do not drop bookings table
    
    # Check if verification_documents exists before adding
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('users')]
    
    if 'verification_documents' not in columns:
        op.add_column('users', sa.Column('verification_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    if 'agent_id' not in [c['name'] for c in inspector.get_columns('properties')]:
         # Should already exist but fk constraint might be missing
         pass

    # op.create_foreign_key(None, 'properties', 'users', ['agent_id'], ['id']) # Re-enable if needed, but safe to skip if mostly consistent
    
    if 'rejection_reason' not in columns:
        op.add_column('users', sa.Column('rejection_reason', sa.String(), nullable=True))

    # agent_status fixing is risky in a transaction if it fails.
    # Skipping the ALTER COLUMN for agent_status to prevent transaction abortion.
    # If the column is VARCHAR, it will work fine with our code as long as we treat it right.
    # If it needs to be ENUM, we should do it in a separate migration or ensure data validity first.

    # Check if index exists before creating
    indexes = [i['name'] for i in inspector.get_indexes('users')]
    if 'ix_users_agent_status' not in indexes:
        op.create_index(op.f('ix_users_agent_status'), 'users', ['agent_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_agent_status'), table_name='users')
    op.alter_column('users', 'agent_status',
               existing_type=sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='agentstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'unverified'::character varying"))
    op.drop_column('users', 'rejection_reason')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('check_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('check_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('guest_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='bookingstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('bookings_property_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bookings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('bookings_pkey'))
    )
    # ### end Alembic commands ###
